# Module manifest for module 'HPEStoragePowerShellToolkit'
# Generated by: Hewlett Packard Enterprise Development LP
#
@{
    RootModule = '.\HPEStorage.psm1'
    ModuleVersion = '3.5.0.0'
    # ID used to uniquely identify this module
    GUID        = '46a7e8f6-729c-45d0-b979-96c684fb28fe'
    Author      = 'Hewlett Packard Enterprise Development LP'
    CompanyName = 'Hewlett Packard Enterprise Development LP'
    Copyright   = '© 2020,2021 Hewlett Packard Enterprise Development LP'
    Description = 'HPE Storage Module providing support for the following platforms; Alletra 9000, Primera, 3PAR, Alletra 6000, and MSA which provides storage administrators the convenience of managing from a PowerShell environment.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    FunctionsToExport = '*'
    CmdletsToExport = '*'
    VariablesToExport = '*'
    AliasesToExport = '*'

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
                # Tags applied to this module. These help with module discovery in online galleries.
                Tags = @('Alletra' , 'Primera' , '3PAR' , 'Nimble', 'MSA') 

                # A URL to the license for this module.
                LicenseUri = 'https://github.com/HewlettPackard/HPEStoragePowerShellToolkit/blob/main/License.txt'

                # A URL to the main website for this project.
                ProjectUri = 'https://github.com/HewlettPackard/HPEStoragePowerShellToolkit/'

                # A URL to an icon representing this module.
                # IconUri = ''

                # ReleaseNotes of this module
                ReleaseNotes = 'Please see the ReadMe.MD and the Changes_*.MD in this modules root directory.'
        } # End of PSData hashtable
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}


